//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP22.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> ExecutionStageId { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> Executor { get; set; }
        public Nullable<int> CountSumm { get; set; }
        public Nullable<decimal> PriceSumm { get; set; }
    
        public virtual ExecutionStage ExecutionStage { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual User User { get; set; }
    }
}
