//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP22.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public Nullable<int> SupProductId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AdmissionProductId { get; set; }
    
        public virtual AdmissionProduct AdmissionProduct { get; set; }
        public virtual SupplierProduct SupplierProduct { get; set; }
    }
}
